#+title: WEng

#+startup: content

* Project Structure
** Paradigms

- Data structure design paradigm (memory addresess sorted by component class).

** Module Structure
*** Modules objective

Modules should be linkable between them and dinamically linkable with the core application.

#+BEGIN_SRC plantuml :file images/modules_dependencies_1.png
@startuml

Rectangle WEngine
Rectangle WInterfaces
Rectangle WObjects
Rectangle WCore
Rectangle WLevel
Rectangle WRender

WInterfaces -[dashed]-> WObjects
WInterfaces -[dashed]-> WCore

WObjects -[dashed]-> WCore

WEngine -[dashed]-> WObjects
WEngine -[dashed]-> WInterfaces
WEngine -[dashed]-> WCore

WLevel -[dashed]-> WInterfaces
WLevel -[dashed]-> WObjects
WLevel -[dashed]-> WCore

WRender -[dashed]-> WInterfaces
WRender -[dashed]-> WObjects
WRender -[dashed]-> WCore

@enduml
#+END_SRC

*** Directory Tree

- Source/ModuleName _(PascalCase)_
      - ModuleName.org
      - CMakeLists.txt (each mmodule will be managed by its own CMakeLists)
      - Source
            - ModuleFile.cpp _(PascalCase)_
      - Include
            - ModuleHeader.h _(PascalCase)_
            - Subdirectories
      - PublicGenerated
      - PrivateGenerated
            - DllDef.hpp
      - CompileGenerated
- ...

*** Namespaces

- All code elements (classes, structs, free operations, etc) should be placed inside a namespace.
- w<name>::<subname>
      - w<name> : <name> is a two letter abbreviation of the external module.
      - <subname> : abstraction name that groups the elements.

* Module List
** WCore
*** WCoreTypes
**** Purpose

Tipos básicos del engine.
Se declaran en WCore para evitar las dependencias cruzadas entre módulos.

**** Files

- WCore/IdPool.hpp
- WCoreTypes/WTexture.hpp
- WCoreTypes/WGeometry.hpp
- WCoreTypes/WEngine.hpp
- WCoreTypes/WMath.hpp
- WCoreTypes/WRenderTypes.hpp

**** Namespaces

- wct::texture
- wct::render
      - Pipeline types (materials)
      - Pipeline parameters types (materials)
      - Lighting types (lights)
- wcr::idpool
      - Weng Core
- wcr::debug
      - debug utilities.

** WEngine
*** Purpose

/Main Module/

WEngine is the starting point of the aplication, the main function will be here.

WEngine will also load each module dinamically, this way the application can be extended using a plugin system, 
modules for ours.

The engine class will reference to other modules in the aplication.

*** WEngRender
**** Purpose

- Setup render subprograms.
- Subprograms are used in the ECS system.
  
**** Files
- WEngRender/WEngRender.hpp
**** Namespaces
- wng::render

** WImporter
*** Purpose

Módulo con las implementaciones necesarias para traducir assets externos en objetos nativos del engine.

**** Files

- WImporter/WImporterRegister.hpp
- WImporter/WImporter.hpp

**** Namespaces

- wim::imp_register
      - Abstracciones para registrar importadores al engine.
      - Un importador registrado puede ser invocado usando tan solo la ruta al archivo.

- wim::importer
      - Objetos Importadores para cada tipo de asset, textura, geometríam etc.

** WInterfaces
** WObjects
Rename to WEngObjects

*** Purpose

Módulo que contiene los objetos que forman la estructura de datos del engine.

*** WObjects
**** Purpose

This module contains all WObject base classes.
From WObject derivates other classes like WComponent, WEntity or WAsset.
Each WObject has a WClass associated. This WClass instance contains relevant data about the WObject class.

WObject is an object that can be tracked by the engine. WObjects has a kind of reflection implemented.

The WObject and WClass system has its own section.

**** Namespace
- weo (WEng Objects) 

*** WComponents

**** Purpose

Componentes almacenan los datos que definen una escena. Se puede pensar en ellos como en una base de datos.
Los componentes están asociados a actores. formando así entidades compuestas de componentes.

**** Files

- WComponents/light/WAmbientLightComponent.hpp
- WComponents/light/WDirectionalLightComponent.hpp
- WComponents/light/WPointLightComponent.hpp

**** Namespace

- wcm : wcomponent namespace
- wcm::light : lights components namespace

*** WAssets

**** Namespace

- was : assets namespace
- was::geometry
  
** WRender
*** WRender
**** Purpose

General Rendering related code.

**** Files

- WRender/*

**** Namespaces

- wrd::render
- wrd::shader

*** WVulkan
**** Purpose

**** Files

**** Namespaces

- wvk::<label>
- wvk::raii
      - directory : WVulkan/WVkRAII

**** WVkRender
***** Purpose
IRender implementation using Vulkan.

** WCollision

/Collision detection/

*** WComponents
**** Purpose
Required components to use the collision system.

**** Namespace
- wcl::component : 

*** WSystems
**** Purpose
Required WSystems to execute the collision system.

**** Namespace
- wcl::system : 

** WPhysics
** WCommand

/Command Module/

This module will contain the system for command registation, base classes and command queues. 
each module will be responsible of its commands creation and registation in the system.

** WWindow
* Template/Reflection
*** WPROPERTY macro
:PROPERTIES:
:CUSTOM_ID: WPROPERTY
:END:
**** Purpose

- Property self knowledge (type, names, ranges, etc).
- Get_ Set_ method access.
- Serialization.

*** WClass.WEngine.hpp

**** Purpose

WClass generation for current WObject.

**** Namespace

- wrf::wclass

*** WOBJECT_BODY macro

* Shaders

- language *Slang*
- [[https://docs.shader-slang.org/en/latest/external/core-module-reference/global-decls/math.html][slang functions reference]]

* WRender
** Static Dynamic Lights UBO updates
:PROPERTIES:
:CUSTOM_ID: StaticDynamicLightsUBOUpdates
:END:

id arrays like :
[SLight 1 , ..., SLight n, Dlight 1,...,Dlight m]

Using a light structure like this allows to perform per frame light updates in a efficiente way.
lightingUBO contains an array for each light type. this array is ensured that will behave lika a dense/sparse set.

So if any update is placed only at the Dynamic lights area, Static lights will never lose its Dense set positions.
All dynamic updates can be done in memory ranges, avoiding that any update range overlaps with the static lights memory area.

- Notes
      - Static lights requires only one UBO (no frames in flight).
      - Dynamic lights could be updated each frame.

* Coding Style

** Classes Initial letter

- T -> templates
- I -> Interfaces
- W -> WEng Object | Engine modules | Engine classes
- E -> Enums


